Style image preview
ImageStyle/ImStyle pull request #46
Opened 2017-10-19 23:08 UTC by jakecarlson1

The source image for the style appears above the photo button and then fades out. Changing the style replaces the image and restarts the animation. Closes #18

2017-10-19 23:11 UTC, ianstenbit requested changes
It looks really nice. Awesome job. Only concern is that it's not super easy to see because the style blends in with the stylized photo. Is there a way to make it 'pop' more? Maybe make it bigger and/or give it a more intense border?

2017-10-19 23:13 UTC, ianjjohnson commented
Still playing around with it. It's so clean. The animation is awesome. Looks so sweet.

2017-10-19 23:31 UTC, jakecarlson1 commented
Think it should be more intense? Previously the boarder was within the bounds of the displayed image.

2017-10-20 01:05 UTC, ianstenbit approved these changes

2017-10-20 01:05 UTC, merged